### PR TITLE
Minor code simplifications via fmt.Sprintf

### PR DESCRIPTION
**Pull request by dswarbrick**

### CODE REVIEW

**Comment by dennwc** [comment]
Not calling `fmt.Sprintf` here is intentional - it avoids unnecessary allocations.

**Comment by dswarbrick** [comment]
Ok, as you wish. I didn't think it was in a performance-critical path.

**Comment by dennwc** [comment]
It might not be on a particularly hot path, but the code is already there, it works, and it's unlikely to ever change for these types. So I'd rather keep it as-is, if there's no strong reason to change it :)

**Comment by dswarbrick** [comment]
I had a bunch of other code cleanup suggestions to propose, e.g. superfluous parentheses, unnecessary typecasts etc - all which would make the code (IMHO) more maintainable and easier to read.

But since the code that those suggestions technically already "works", I shall refrain from offering any more suggestions.

**Pull request closed without merging**
